### ISSUE TITLE
wayid not found

### ISSUE THREAD

**Issue by gknisely** [valhalla/loki#115]
No wayid is found for the following LL, but the LL is right at the intersection of Robert Davey Jr Dr & Aughinbaugh Way.

2016/03/30 11:23:12.697676 [ERROR] No closest edge found for this stop: Aughinbaugh Way:Robert Davey Jr Dr way Id =  LL= 37.742889,-122.2499626381920 tile -122.250000, 37.500000, -122.000000, 37.750000

**Comment by dnesbitt61** [comment]
This is now an issue with transitbuilder. Loki finds the wayId but transitbuilder cannot since the start or end node does not lie in the tile.  Also, looks like that Log statement isn't quite right - the wayId is appended to the longitude.

**Comment by kevinkreiser** [comment]
right yeah.. a previous version of `loki` would have forced it to be in the tile even if a better result was not in the tile. at this point we'll need to update `mjolnir::transitbuilder` to be robust to that
