### ISSUE TITLE
closest point regression

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/loki#123]
it seems somehow the closest point logic has regressed. clicking around near a way you can get the code to snap non-orthogonally so that its actually not the closest point to the input...

nothing has changed here recently so perhaps the shape encoding has had an impact

**Comment by ptpt** [comment]
Is this an example of the issue?

I notice this slight off-center projection has been there for a while, which is especially obvious in map matching (see screenshot below).

![screenshot from 2016-05-21 12-18-20](https://cloud.githubusercontent.com/assets/87357/15447804/705b224e-1f4e-11e6-9840-afbf289233f9.png)

![screenshot from 2016-05-21 12-25-38](https://cloud.githubusercontent.com/assets/87357/15447887/a139aa0a-1f50-11e6-930b-ba43cb669b72.png)

**Comment by kevinkreiser** [comment]
yep @ptpt that is exactly it. very sorry about the regression, i'm not quite sure yet how it slipped in there! i'll take a look at that after i wrap up the final bits of getting valhalla in PPA

**Comment by kevinkreiser** [comment]
yeah i have always had that in the back of my mind. however i had never noticed it before and the calculation has always been a planar approximation of a sphere. maybe we just never noticed it until now?

**Comment by ptpt** [comment]
It's been there for a while. See the screenshot in this issue https://github.com/valhalla/meili/issues/5

North areas this issue is more obvious.

**Comment by TeXitoi** [comment]
To fix that, you should use the cos rescale as in `DistanceApproximator` in `project()`.
