### ISSUE TITLE
Regression in EdgeSearch

### ISSUE THREAD

**Issue by fsaric** [valhalla/loki#48]
It seems that a regression was introduced in a3735912d359f03734cd1b0188c1e4daecb0691d.

You can reproduce the bug by downloading croatia-latest.pbf, running pbfgraphbuilder and running pathtest with the following parameters:
```
$ ./pathtest --config conf/valhalla.json -t auto -o 45,16 -d 45,16.5
2015/07/26 14:07:43.998750 [INFO] routetype: auto
terminate called after throwing an instance of 'std::runtime_error'
  what():  GraphTile NodeInfo index out of bounds: 778385,2,244 nodecount= 86
Aborted (core dumped)
```

The problem seems to be here:

https://github.com/valhalla/loki/blob/00f6ef1a71e1463c76b2210a41c96820ba9187a1/src/loki/search.cc#L238

In a rare case the edge endnode can be in a different tile (a rare occurence) so `tile->node` fails to find the edge endnode.

**Comment by dnesbitt61** [comment]
Thanks for identifying this issue. We will get a fix in for it tomorrow.

**Comment by kevinkreiser** [comment]
thanks again sorry for the regression.. a bit scatter brained of late..
